### ISSUE TITLE
Error generating new EFI

### ISSUE THREAD

**Issue by wstroftgithub** [Gytch/oc-gen-windows#1]
When i pick the files i need for the EFI to work, i hit the New EFI button, but a blue line just blinks at the bottom of the button and reacted if i didn't do anything. Any fix? This error is happening to the three buttons "New EFI", "Generate" and "Validate Settings".

**Comment by wstroftgithub** [comment]
> When i pick the files i need for the EFI to work, i hit the New EFI button, but a blue line just blinks at the bottom of the button and reacted if i didn't do anything. Any fix? This error is happening to the three buttons "New EFI", "Generate" and "Validate Settings".

**Comment by wstroftgithub** [comment]
forgot to put flare lol

**Comment by Gytch** [comment]
Please read the main README.md it says App has no functionalities

**Comment by Gytch** [comment]
This is only UI Design, I'm coding the app as soon as possible
